
//------------------TODOS-----------------------------//

###
GET http://localhost:3000/listadoUsuarios

//------------------UNO-------------------------------//

### 
GET http://localhost:3000/unoUsuario/613ee69c26cc5c0f67ccb672

//------------------REGISTRAR--------------------------//
###
POST http://localhost:3000/registrarUsuario 
Content-Type: application/json

{
    "nombre":"Nelson",
    "apellido": "Rivas",
    "direccion":"Chalatenango"
}

//------------------EDITAR--------------------------//
### 
PUT http://localhost:3000/editarUsuario/613ee5e978208c48f56e9493
Content-Type: application/json

{
    "nombre": "Nicole",
    "apellido": "Cabañas",
    "direccion": "Chalatenango"
}

//------------------ELIMINAR--------------------------//
###
DELETE http://localhost:3000/eliminarUsuario/614974d62dbf7328da6f73c4